config:
  # If a property in the configuration is deprecated, that'll fail Detekt execution.
  warningsAsErrors: true


processors:
  # Blanket disable processors as they are not used.
  # Stats would show up in HTML report, but since that's not mergeable it has little value per module.
  active: false


console-reports:
  exclude:
    # Disabled because I don't want to see what kind of reports are generate every time I run detekt.
    - 'NotificationReport'
    # Disabled because it's very verbose. 
    - 'FindingsReport'
    # Disabled because it's very verbose, even more so than FindingsReport.
    - 'FileBasedFindingsReport'
    # Enabled, because this gives enough context to see the problems.
    #- 'LiteFindingsReport'


naming:

  FunctionMaxLength:
    ignoreAnnotated:
      # Test names in JUnit 5 are ok to be long as they're likely sentences.
      - 'org.junit.jupiter.api.Test'
      - 'org.junit.jupiter.api.TestFactory'
      - 'org.junit.jupiter.api.RepeatedTest'
      - 'org.junit.jupiter.params.ParameterizedTest'


style:

  MultilineRawStringIndentation:
    # Change indent size, because the indentation character is TAB.
    indentSize: 1

  NoTabs:
    # I'm a tab guy, I don't pay for space in advance.
    active: false

  UnnecessaryInnerClass:
    ignoreAnnotated:
      - 'org.junit.jupiter.api.Nested'

  RedundantVisibilityModifierRule:
    active: false # STOPSHIP review for library
  UseDataClass:
    active: false # STOPSHIP review for library

comments:
  UndocumentedPublicClass:
    active: false # STOPSHIP review for library
  UndocumentedPublicFunction:
    active: false # STOPSHIP review for library
  UndocumentedPublicProperty:
    active: false # STOPSHIP review for library
