name: "CI Publish"

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

jobs:
  test-results:
    name: "CI Publish Followup"
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    runs-on: ubuntu-latest
    timeout-minutes: 1

    permissions: { }

    steps:
      - name: "TODO"
        shell: bash
        run: 'false'
